# Generated by Django 3.2.4 on 2021-11-17 08:54

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='DdtData',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('desc', models.CharField(max_length=255, verbose_name='说明')),
            ],
            options={
                'verbose_name': '数据驱动',
                'verbose_name_plural': '数据驱动',
            },
        ),
        migrations.CreateModel(
            name='Product',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('productName', models.CharField(max_length=64, verbose_name='项目名称')),
                ('productDesc', models.CharField(blank=True, max_length=200, null=True, verbose_name='项目描述')),
                ('producter', models.CharField(blank=True, max_length=200, null=True, verbose_name='项目负责人')),
                ('create_time', models.DateTimeField(auto_now=True, verbose_name='创建时间')),
            ],
            options={
                'verbose_name': '项目管理',
                'verbose_name_plural': '项目管理',
            },
        ),
        migrations.CreateModel(
            name='SeleniumHubServer',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200, verbose_name='名称')),
                ('hostinfo', models.CharField(max_length=200, verbose_name='远程地址')),
                ('create_time', models.DateTimeField(auto_now=True, verbose_name='创建时间')),
            ],
            options={
                'verbose_name': 'SeleniumHUB管理',
                'verbose_name_plural': 'SeleniumHUB管理',
            },
        ),
        migrations.CreateModel(
            name='WebCase',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('caseName', models.CharField(max_length=128, verbose_name='用例名称')),
                ('browser', models.CharField(choices=[('Chrome', 'Chrome'), ('Firefox', 'Firefox'), ('IE', 'IE'), ('Edge', 'Edge')], max_length=64, verbose_name='浏览器')),
                ('Product', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='webtest.product', verbose_name='所属项目')),
                ('SeleniumHubServer', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='webtest.seleniumhubserver', verbose_name='SeleniumServer服务器')),
                ('WebCase', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='webtest.webcase', verbose_name='前置用例步骤')),
            ],
            options={
                'verbose_name': 'WEB测试用例',
                'verbose_name_plural': 'WEB测试用例',
            },
        ),
        migrations.CreateModel(
            name='WebCaseStep',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('sort', models.IntegerField(default=1, verbose_name='执行顺序')),
                ('command', models.CharField(choices=[('click', 'click'), ('close', 'close'), ('double_click', 'double_click'), ('drag_and_drop_to_object', 'drag_and_drop_to_object'), ('execute_script', 'execute_script'), ('execute_async_script', 'execute_async_script'), ('mouse_over', 'mouse_over'), ('open', 'open'), ('pause', 'pause'), ('select', 'select'), ('select_frame', 'select_frame'), ('switch_to_parent_frame', 'switch_to_parent_frame'), ('select_window', 'select_window'), ('send_keys', 'send_keys'), ('store', 'store'), ('store_text', 'store_text'), ('store_title', 'store_title'), ('store_value', 'store_value'), ('store_xpath_count', 'store_xpath_count'), ('add_cookie', 'add_cookie'), ('submit', 'submit'), ('wait_for_element_not_visible', 'wait_for_element_not_visible'), ('wait_for_element_present', 'wait_for_element_present'), ('wait_for_element_visible', 'wait_for_element_visible'), ('assert_variable', 'assert_variable'), ('assert_title_is', 'assert_title_is'), ('assert_title_contains', 'assert_title_contains'), ('assert_url_contains', 'assert_url_contains'), ('assert_url_matches', 'assert_url_matches'), ('assert_url_to_be', 'assert_url_to_be'), ('assert_url_changes', 'assert_url_changes'), ('assert_presence_of_element_located', 'assert_presence_of_element_located'), ('assert_presence_of_all_elements_located', 'assert_presence_of_all_elements_located'), ('assert_visibility_of_element_located', 'assert_visibility_of_element_located'), ('assert_invisibility_of_element_located', 'assert_invisibility_of_element_located'), ('assert_invisibility_of_element', 'assert_invisibility_of_element'), ('assert_visibility_of', 'assert_visibility_of'), ('assert_visibility_of_any_elements_located', 'assert_visibility_of_any_elements_located'), ('assert_visibility_of_all_elements_located', 'assert_visibility_of_all_elements_located'), ('assert_element_to_be_clickable', 'assert_element_to_be_clickable'), ('assert_staleness_of', 'assert_staleness_of'), ('assert_text_to_be_present_in_element', 'assert_text_to_be_present_in_element'), ('assert_text_to_be_present_in_element_value', 'assert_text_to_be_present_in_element_value'), ('assert_frame_to_be_available_and_switch_to_it', 'assert_frame_to_be_available_and_switch_to_it'), ('assert_element_to_be_selected', 'assert_element_to_be_selected'), ('assert_element_located_to_be_selected', 'assert_element_located_to_be_selected'), ('assert_element_located_selection_state_to_be', 'assert_element_located_selection_state_to_be'), ('assert_number_of_windows_to_be', 'assert_number_of_windows_to_be'), ('assert_alert_is_present', 'assert_alert_is_present'), ('assert_text_of_alert', 'assert_text_of_alert')], max_length=255, verbose_name='步骤调用命令')),
                ('desc', models.CharField(max_length=255, verbose_name='步骤描述')),
                ('target', models.CharField(max_length=255, verbose_name='操作对象[页面元素、具体值..]')),
                ('value', models.CharField(max_length=255, verbose_name='数据项')),
                ('WebCase', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='webtest.webcase', verbose_name='测试用例')),
            ],
            options={
                'verbose_name': '测试步骤',
                'verbose_name_plural': '测试步骤',
                'ordering': ('sort',),
            },
        ),
        migrations.CreateModel(
            name='DdtParams',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('setname', models.CharField(max_length=64, verbose_name='参数名')),
                ('setvalue', models.CharField(max_length=1024, verbose_name='参数值')),
                ('DdtData', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='webtest.ddtdata', verbose_name='数据驱动项')),
            ],
            options={
                'verbose_name': '数据驱动数据项',
                'verbose_name_plural': '数据驱动数据项',
            },
        ),
        migrations.AddField(
            model_name='ddtdata',
            name='WebCase',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='webtest.webcase', verbose_name='测试用例'),
        ),
        migrations.CreateModel(
            name='CaseContext',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('setname', models.CharField(max_length=64, verbose_name='参数名')),
                ('setvalue', models.CharField(max_length=1024, verbose_name='参数值')),
                ('WebCase', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='webtest.webcase', verbose_name='测试用例')),
            ],
            options={
                'verbose_name': '上下文参数定义',
                'verbose_name_plural': '上下文参数定义',
            },
        ),
    ]
