# Generated by Django 3.2.4 on 2021-11-17 09:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('webtest', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='webcasestep',
            name='desc',
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name='步骤描述'),
        ),
        migrations.AlterField(
            model_name='webcasestep',
            name='target',
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name='操作对象[页面元素、具体值..]'),
        ),
        migrations.AlterField(
            model_name='webcasestep',
            name='value',
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name='数据项'),
        ),
    ]
