# Generated by Django 3.2.4 on 2021-11-19 09:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('webtest', '0002_auto_20211117_1707'),
    ]

    operations = [
        migrations.AlterField(
            model_name='webcase',
            name='browser',
            field=models.CharField(choices=[('chrome', 'chrome'), ('firefox', 'firefox'), ('ie', 'ie'), ('edge', 'edge')], max_length=64, verbose_name='浏览器'),
        ),
        migrations.AlterField(
            model_name='webcasestep',
            name='command',
            field=models.CharField(choices=[('click', '点击'), ('close', 'close'), ('double_click', 'double_click'), ('drag_and_drop_to_object', 'drag_and_drop_to_object'), ('execute_script', 'execute_script'), ('execute_async_script', 'execute_async_script'), ('mouse_over', 'mouse_over'), ('open', 'open'), ('pause', 'pause'), ('select', 'select'), ('select_frame', 'select_frame'), ('switch_to_parent_frame', 'switch_to_parent_frame'), ('select_window', 'select_window'), ('send_keys', 'send_keys'), ('store', 'store'), ('store_text', 'store_text'), ('store_title', 'store_title'), ('store_value', 'store_value'), ('store_xpath_count', 'store_xpath_count'), ('add_cookie', 'add_cookie'), ('submit', 'submit'), ('wait_for_element_not_visible', 'wait_for_element_not_visible'), ('wait_for_element_present', 'wait_for_element_present'), ('wait_for_element_visible', 'wait_for_element_visible'), ('assert_variable', 'assert_variable'), ('assert_title_is', 'assert_title_is'), ('assert_title_contains', 'assert_title_contains'), ('assert_url_contains', 'assert_url_contains'), ('assert_url_matches', 'assert_url_matches'), ('assert_url_to_be', 'assert_url_to_be'), ('assert_url_changes', 'assert_url_changes'), ('assert_presence_of_element_located', 'assert_presence_of_element_located'), ('assert_presence_of_all_elements_located', 'assert_presence_of_all_elements_located'), ('assert_visibility_of_element_located', 'assert_visibility_of_element_located'), ('assert_invisibility_of_element_located', 'assert_invisibility_of_element_located'), ('assert_invisibility_of_element', 'assert_invisibility_of_element'), ('assert_visibility_of', 'assert_visibility_of'), ('assert_visibility_of_any_elements_located', 'assert_visibility_of_any_elements_located'), ('assert_visibility_of_all_elements_located', 'assert_visibility_of_all_elements_located'), ('assert_element_to_be_clickable', 'assert_element_to_be_clickable'), ('assert_staleness_of', 'assert_staleness_of'), ('assert_text_to_be_present_in_element', 'assert_text_to_be_present_in_element'), ('assert_text_to_be_present_in_element_value', 'assert_text_to_be_present_in_element_value'), ('assert_frame_to_be_available_and_switch_to_it', 'assert_frame_to_be_available_and_switch_to_it'), ('assert_element_to_be_selected', 'assert_element_to_be_selected'), ('assert_element_located_to_be_selected', 'assert_element_located_to_be_selected'), ('assert_element_located_selection_state_to_be', 'assert_element_located_selection_state_to_be'), ('assert_number_of_windows_to_be', 'assert_number_of_windows_to_be'), ('assert_alert_is_present', 'assert_alert_is_present'), ('assert_text_of_alert', 'assert_text_of_alert')], max_length=255, verbose_name='步骤调用命令'),
        ),
    ]
