# Generated by Django 3.2.4 on 2021-11-05 07:12

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('apitest', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='apicase',
            options={'verbose_name': '接口测试用例', 'verbose_name_plural': '接口测试用例'},
        ),
        migrations.AlterField(
            model_name='httprequest',
            name='CookieTemplate',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='apitest.cookietemplate', verbose_name='Cookie信息'),
        ),
        migrations.AlterField(
            model_name='httprequest',
            name='HeaderTemplate',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='apitest.headertemplate', verbose_name='请求头'),
        ),
    ]
