# Generated by Django 3.2.4 on 2021-11-17 08:54

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('apitest', '0003_auto_20211105_1644'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='extractoptions',
            options={'verbose_name': '数据抽取项', 'verbose_name_plural': '数据抽取项'},
        ),
    ]
