# Generated by Django 3.2.4 on 2021-11-19 09:12

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='AppCase',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('caseName', models.CharField(max_length=128, verbose_name='用例名称')),
            ],
            options={
                'verbose_name': 'APP测试用例',
                'verbose_name_plural': 'APP测试用例',
            },
        ),
        migrations.CreateModel(
            name='AppiumServer',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200, verbose_name='名称')),
                ('hostinfo', models.CharField(max_length=200, verbose_name='远程地址')),
                ('create_time', models.DateTimeField(auto_now=True, verbose_name='创建时间')),
            ],
            options={
                'verbose_name': 'AppiumServer管理',
                'verbose_name_plural': 'AppiumServer管理',
            },
        ),
        migrations.CreateModel(
            name='AppManage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('appname', models.CharField(max_length=200, verbose_name='应用名称')),
                ('appversion', models.CharField(max_length=200, verbose_name='应用版本')),
                ('platformVersion', models.CharField(choices=[('Android', 'Android'), ('IOS', 'IOS')], default='Android', max_length=200, verbose_name='平台')),
                ('create_time', models.DateTimeField(auto_now=True, verbose_name='创建时间')),
            ],
            options={
                'verbose_name': '应用管理',
                'verbose_name_plural': '应用管理',
            },
        ),
        migrations.CreateModel(
            name='DdtData',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('desc', models.CharField(max_length=255, verbose_name='说明')),
                ('AppCase', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='apptest.appcase', verbose_name='测试用例')),
            ],
            options={
                'verbose_name': '数据驱动',
                'verbose_name_plural': '数据驱动',
            },
        ),
        migrations.CreateModel(
            name='Product',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('productName', models.CharField(max_length=64, verbose_name='项目名称')),
                ('productDesc', models.CharField(blank=True, max_length=200, null=True, verbose_name='项目描述')),
                ('producter', models.CharField(blank=True, max_length=200, null=True, verbose_name='项目负责人')),
                ('create_time', models.DateTimeField(auto_now=True, verbose_name='创建时间')),
            ],
            options={
                'verbose_name': '项目管理',
                'verbose_name_plural': '项目管理',
            },
        ),
        migrations.CreateModel(
            name='Device',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('deviceremark', models.CharField(max_length=200, verbose_name='设备标题')),
                ('platformName', models.CharField(choices=[('Android', 'Android'), ('IOS', 'IOS')], default='Android', max_length=200, verbose_name='设备平台')),
                ('platformVersion', models.CharField(max_length=200, verbose_name='版本')),
                ('deviceName', models.CharField(max_length=200, verbose_name='设备名称')),
                ('create_time', models.DateTimeField(auto_now=True, verbose_name='创建时间')),
                ('AppiumServer', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='apptest.appiumserver', verbose_name='AppiumServer信息')),
            ],
            options={
                'verbose_name': '设备管理',
                'verbose_name_plural': '设备管理',
            },
        ),
        migrations.CreateModel(
            name='DdtParams',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('setname', models.CharField(max_length=64, verbose_name='参数名')),
                ('setvalue', models.CharField(max_length=1024, verbose_name='参数值')),
                ('DdtData', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='apptest.ddtdata', verbose_name='数据驱动项')),
            ],
            options={
                'verbose_name': '数据驱动数据项',
                'verbose_name_plural': '数据驱动数据项',
            },
        ),
        migrations.CreateModel(
            name='CaseContext',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('setname', models.CharField(max_length=64, verbose_name='参数名')),
                ('setvalue', models.CharField(max_length=1024, verbose_name='参数值')),
                ('AppCase', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='apptest.appcase', verbose_name='测试用例')),
            ],
            options={
                'verbose_name': '上下文参数定义',
                'verbose_name_plural': '上下文参数定义',
            },
        ),
        migrations.CreateModel(
            name='AppParams',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('setname', models.CharField(max_length=64, verbose_name='参数名')),
                ('setvalue', models.CharField(max_length=1024, verbose_name='参数值')),
                ('AppManage', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='apptest.appmanage', verbose_name='应用')),
            ],
            options={
                'verbose_name': '应用参数项',
                'verbose_name_plural': '应用参数项',
            },
        ),
        migrations.CreateModel(
            name='AppCaseStep',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('sort', models.IntegerField(default=1, verbose_name='执行顺序')),
                ('command', models.CharField(choices=[('assert_variable', 'assert_variable'), ('assert_activity', 'assert_activity'), ('assert_text', '判断元素文本'), ('assert_text_contains', 'assert_text_contains'), ('assert_tag_name', 'assert_tag_name'), ('background_app', 'background_app'), ('back', 'back'), ('click', 'click'), ('clear', 'clear'), ('send_keys', 'send_keys'), ('store_attribute', 'store_attribute'), ('store_css_property', 'store_css_property'), ('wait_implicitly', 'wait_implicitly'), ('wait_time', 'wait_time'), ('wait_activity', '等待activity加载')], max_length=255, verbose_name='步骤调用命令')),
                ('desc', models.CharField(blank=True, max_length=255, null=True, verbose_name='步骤描述')),
                ('target', models.CharField(blank=True, max_length=255, null=True, verbose_name='操作对象[页面元素、具体值..]')),
                ('value', models.CharField(blank=True, max_length=255, null=True, verbose_name='数据项')),
                ('AppCase', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='apptest.appcase', verbose_name='测试用例')),
            ],
            options={
                'verbose_name': '测试步骤',
                'verbose_name_plural': '测试步骤',
                'ordering': ('sort',),
            },
        ),
        migrations.AddField(
            model_name='appcase',
            name='AppManage',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='apptest.appmanage', verbose_name='所属应用'),
        ),
        migrations.AddField(
            model_name='appcase',
            name='SeleniumHubServer',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='apptest.device', verbose_name='运行设备'),
        ),
        migrations.AddField(
            model_name='appcase',
            name='WebCase',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='apptest.appcase', verbose_name='前置用例步骤'),
        ),
    ]
